#!/bin/sh

DIR="$( cd "$( dirname "$0" )" && pwd )"

for n in `ls -A $DIR`; do
	if [ $n != '.git' ] && [ $n != 'README.md' ] && [ $n != $(basename $0) ]; then
		echo "Installed $n"
		ln -nfs $DIR/$n ~/$n
	fi
done

# I may need to add pathogen install commands here

# Source all of my dotfiles
source ~/.bashrc
